### ISSUE TITLE
Fix HealthCheck

### ISSUE THREAD

**Issue by dennzo** [dennzo/the-printer#9]
```log
file:///home/node/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:58
        _Callback_error.set(this, new ProtocolError());
                                  ^

ProtocolError: Protocol error (Page.printToPDF): paper width is zero or negative
    at new Callback (file:///home/node/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:58:35)
    at CallbackRegistry.create (file:///home/node/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:103:26)
    at Connection._rawSend (file:///home/node/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:212:26)
    at CDPSessionImpl.send (file:///home/node/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:419:78)
    at CDPPage.createPDFStream (file:///home/node/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:720:88)
    at CDPPage.pdf (file:///home/node/app/node_modules/puppeteer-core/lib/esm/puppeteer/common/Page.js:746:37)
    at PdfAction (file:///home/node/app/src/Action/PdfAction.js:29:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Exit code: 1.
```

Current Workaround is deactivating the health check in the docker-compose file.

```yaml
    healthcheck:
      test: [ "CMD", "none" ]
```

**Comment by dennzo** [comment]
now works again!
